import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import * as api from './api/api'
import { useState } from 'react'

interface userType {
  name: string
}

const Home: NextPage = () => {
  const [data, setData] = useState<string>('')

  async function posting() {
    const user = { name: data }
    console.log(user)
    const res = await api.post('/api/users', user)
    console.log('post 응답', res)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl font-bold underline bg-red-500">
        Welcome Next
      </div>
      <input
        type="text"
        value={data}
        onChange={(e) => {
          setData(e.target.value)
        }}
      />
      <button onClick={posting}>클릭</button>
    </div>
  )
}

export default Home
