import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'
import { Header } from '../components/header/Header'
import { Footer } from '../components/Footer'

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>DAECHI MATH ACADEMY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Footer />
    </Layout>
  )
}

export default Home
